import { expect } from 'chai';
import request from 'supertest';
import { createTestApp } from '../helpers/createTestApp.js';
import { issueCSRFToken } from '../../middleware/csrf.middleware.js';

const app = createTestApp();

describe('CSRF Protection', () => {

    // --- issueCSRFToken ---

    it('should generate a 64-character hex string', () => {
        const token = issueCSRFToken();
        expect(token).to.be.a('string');
        expect(token).to.have.lengthOf(64);
        expect(token).to.match(/^[a-f0-9]{64}$/);
    });

    it('should generate a unique token on each call', () => {
        const token1 = issueCSRFToken();
        const token2 = issueCSRFToken();
        expect(token1).to.not.equal(token2);
    });

    // --- Safe methods ---

    it('should accept GET request with no CSRF token', async () => {
        const res = await request(app).get('/api/csrf-protected');
        expect(res.status).to.equal(200);
    });

    it('should accept HEAD request with no CSRF token', async () => {
        const res = await request(app).head('/api/csrf-protected');
        expect(res.status).to.equal(200);
    });

    it('should accept OPTIONS request with no CSRF token', async () => {
        const res = await request(app).options('/api/csrf-protected');
        expect(res.status).to.equal(200);
    });

    // --- POST validation ---

    it('should return 403 with no CSRF token', async () => {
        const res = await request(app).post('/api/csrf-protected');
        expect(res.status).to.equal(403);
    });

    it('should return 403 with missing cookie', async () => {
        const res = await request(app).post('/api/csrf-protected')
            .set('X-CSRF-Token', 'abc123testtoken');
        expect(res.status).to.equal(403);
    });

    it('should return 403 with missing header', async () => {
        const res = await request(app).post('/api/csrf-protected')
            .set('Cookie', 'csrfToken=abc123testtoken');
        expect(res.status).to.equal(403);
    });

    it('should return 403 with non-matching tokens of different lengths', async () => {
        const res = await request(app).post('/api/csrf-protected')
            .set('Cookie', 'csrfToken=abc123testtoken')
            .set('X-CSRF-Token', 'nonmatchingtoken');
        expect(res.status).to.equal(403);
    });

    it('should return 403 with same-length tokens that have different values', async () => {
        const res = await request(app).post('/api/csrf-protected')
            .set('Cookie', 'csrfToken=aaaaaaaaaaaaaaaa')
            .set('X-CSRF-Token', 'bbbbbbbbbbbbbbbb');
        expect(res.status).to.equal(403);
    });

    it('should return 403 when tokens share a prefix but differ at the end', async () => {
        const res = await request(app).post('/api/csrf-protected')
            .set('Cookie', 'csrfToken=abc123testtokenA')
            .set('X-CSRF-Token', 'abc123testtokenB');
        expect(res.status).to.equal(403);
    });

    it('should return 403 with an empty cookie token', async () => {
        const res = await request(app).post('/api/csrf-protected')
            .set('Cookie', 'csrfToken=')
            .set('X-CSRF-Token', 'abc123testtoken');
        expect(res.status).to.equal(403);
    });

    it('should accept matching cookie and header CSRF token', async () => {
        const res = await request(app).post('/api/csrf-protected')
            .set('Cookie', 'csrfToken=abc123testtoken')
            .set('X-CSRF-Token', 'abc123testtoken');
        expect(res.status).to.equal(200);
    });

    it('should accept a token generated by issueCSRFToken', async () => {
        const token = issueCSRFToken();
        const res = await request(app).post('/api/csrf-protected')
            .set('Cookie', `csrfToken=${token}`)
            .set('X-CSRF-Token', token);
        expect(res.status).to.equal(200);
    });

    // --- PUT validation ---

    it('should return 403 on PUT with no CSRF token', async () => {
        const res = await request(app).put('/api/csrf-protected');
        expect(res.status).to.equal(403);
    });

    it('should return 403 on PUT with non-matching tokens', async () => {
        const res = await request(app).put('/api/csrf-protected')
            .set('Cookie', 'csrfToken=abc123testtoken')
            .set('X-CSRF-Token', 'wrongtoken123456');
        expect(res.status).to.equal(403);
    });

    it('should accept PUT with matching CSRF token', async () => {
        const res = await request(app).put('/api/csrf-protected')
            .set('Cookie', 'csrfToken=abc123testtoken')
            .set('X-CSRF-Token', 'abc123testtoken');
        expect(res.status).to.equal(200);
    });

    // --- DELETE validation ---

    it('should return 403 on DELETE with no CSRF token', async () => {
        const res = await request(app).delete('/api/csrf-protected');
        expect(res.status).to.equal(403);
    });

    it('should accept DELETE with matching CSRF token', async () => {
        const res = await request(app).delete('/api/csrf-protected')
            .set('Cookie', 'csrfToken=abc123testtoken')
            .set('X-CSRF-Token', 'abc123testtoken');
        expect(res.status).to.equal(200);
    });

});
